### ISSUE TITLE
Restructure project code into nice components

### ISSUE THREAD

**Issue by Niraj-Kamdar** [Electronic-Hobby-Center/Smart-Home-Automation-System#1]
Currently, project has every file in root directory which isn't a good way to organize a project. You should refactor your code in following way:
/static/assets/image for images
/static/css for css
/static/js for js

You can keep index.html on root directory since this seems front-end only project.
Note: Don't push code directly to the repo. Open a pull-request instead. So, that we can review code before it get merge.

**Comment by RoneelV** [comment]
I feel static folder will be bit too ceremonious since whole app is static, without build step. I've pushed the code with simpler structure to new branch. Hope that's fine
